version: "3"

services:
  django_recipe_api:
    build:
      context: . 
    ports:
      - "8000:8000"
      
    volumes: 
      - .:/social_app_api
    command: sh -c "python manage.py runserver 0.0.0.0:8000" 